-- Your SQL goes here
CREATE TABLE IF NOT EXISTS dir_entrys
(
    the_path BLOB PRIMARY KEY NOT NULL,
    the_meta BLOB NOT NULL
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS db_meta
(
    the_key BLOB PRIMARY KEY NOT NULL,
    the_value BLOB NOT NULL
) WITHOUT ROWID;
