mod common;
use common::*;

#[test]
fn block_11_parse_matrix_a() {
    let _ = parse_ok("alpha beta");
    let _ = parse_ok("gamma delta");
    let _ = parse_ok("epsilon zeta");
    let _ = parse_ok("eta theta");
    let _ = parse_ok("iota kappa");
    let _ = parse_ok("lambda mu");
    let _ = parse_ok("nu xi");
    let _ = parse_ok("omicron pi");
    let _ = parse_ok("rho sigma");
    let _ = parse_ok("tau upsilon");
    let _ = parse_ok("phi chi");
    let _ = parse_ok("psi omega");
    let _ = parse_ok("folder:src ext:rs");
    let _ = parse_ok("folder:src dm:today");
    let _ = parse_ok("ext:md dc:pastweek");
    let _ = parse_ok("size:>1mb alpha");
    let _ = parse_ok("size:>=2gb beta");
    let _ = parse_ok("size:<3kb gamma");
    let _ = parse_ok("size:<=4tb delta");
    let _ = parse_ok("size:=42 epsilon");
    let _ = parse_ok("size:!=7 zeta");
    let _ = parse_ok("alpha|beta");
    let _ = parse_ok("alpha OR beta");
    let _ = parse_ok("!alpha beta");
    let _ = parse_ok("alpha ! beta");
    let _ = parse_ok("(alpha beta)|gamma");
    let _ = parse_ok("alpha|(beta gamma)");
    let _ = parse_ok("<alpha beta>|<gamma>");
    let _ = parse_ok("(alpha (beta|gamma)) delta");
    let _ = parse_ok("folder:src (!ext:md) alpha");
    let _ = parse_ok("(folder:src folder:components) ext:tsx");
    let _ = parse_ok("regex:^a.* alpha");
    let _ = parse_ok("regex:.*rs$ beta");
    let _ = parse_ok("parent:src gamma");
    let _ = parse_ok("infolder:src delta");
    let _ = parse_ok("file:Cargo.toml epsilon");
    let _ = parse_ok("folder:target zeta");
    let _ = parse_ok("ext:png;jpg;gif eta");
    let _ = parse_ok("ext:rs;toml;md theta");
    let _ = parse_ok("folder:assets iota");
    let _ = parse_ok("file:README.md kappa");
    let _ = parse_ok("file:LICENSE lambda");
    let _ = parse_ok("folder:src-tauri mu");
    let _ = parse_ok("alpha beta gamma");
    let _ = parse_ok("delta epsilon zeta");
    let _ = parse_ok("eta theta iota");
    let _ = parse_ok("kappa lambda mu");
    let _ = parse_ok("nu xi omicron");
    let _ = parse_ok("pi rho sigma");
    let _ = parse_ok("tau upsilon phi");
    let _ = parse_ok("chi psi omega");
    let _ = parse_ok("alpha beta gamma delta");
    let _ = parse_ok("epsilon zeta eta theta");
    let _ = parse_ok("iota kappa lambda mu");
    let _ = parse_ok("nu xi omicron pi");
    let _ = parse_ok("rho sigma tau upsilon");
    let _ = parse_ok("phi chi psi omega");
    let _ = parse_ok("alpha|beta|gamma");
    let _ = parse_ok("alpha OR beta OR gamma");
    let _ = parse_ok("alpha ! beta ! gamma");
    let _ = parse_ok("!alpha !beta gamma");
    let _ = parse_ok("(alpha beta) | (gamma delta)");
    let _ = parse_ok("alpha (beta | gamma) delta");
    let _ = parse_ok("(alpha | beta) gamma delta");
    let _ = parse_ok("<alpha beta> | <gamma delta>");
    let _ = parse_ok("folder:src ext:rs alpha beta");
    let _ = parse_ok("folder:src alpha !ext:md");
    let _ = parse_ok("folder:src ! ext:md");
    let _ = parse_ok("folder:src (!ext:md)");
    let _ = parse_ok("(folder:src folder:components) OR ext:tsx");
    let _ = parse_ok("folder:src ext:rs !regex:^test_.*");
    let _ = parse_ok("folder:src !ext:md regex:.*\\.rs$");
    let _ = parse_ok("infolder:src regex:.*\\.rs$");
    let _ = parse_ok("parent:src regex:.*\\.rs$");
    let _ = parse_ok("folder:src regex:.*\\.rs$ !ext:md");
    let _ = parse_ok("folder:src regex:.*\\.rs$ ! ext:md");
    let _ = parse_ok("folder:src ! ext:md regex:.*\\.rs$");
    let _ = parse_ok("folder:src (! ext:md) regex:.*\\.rs$");
    let _ = parse_ok("folder:src (! (ext:md)) regex:.*\\.rs$");
    let _ = parse_ok("(folder:src !ext:md) regex:.*\\.rs$");
    let _ = parse_ok("(folder:src ! ext:md) regex:.*\\.rs$");
    let _ = parse_ok("(folder:src (!ext:md)) regex:.*\\.rs$");
    let _ = parse_ok("(folder:src (! ext:md)) regex:.*\\.rs$");
    let _ = parse_ok("folder:src (regex:.*\\.rs$ !ext:md)");
    let _ = parse_ok("folder:src (regex:.*\\.rs$ ! ext:md)");
    let _ = parse_ok("folder:src (regex:.*\\.rs$ (!ext:md))");
    let _ = parse_ok("folder:src (regex:.*\\.rs$ (! ext:md))");
}

#[test]
fn block_12_parse_matrix_b() {
    let _ = parse_ok("dc:2020/01/01-2020/12/31 alpha");
    let _ = parse_ok("dm:2021/01/01-2021/02/01 beta");
    let _ = parse_ok("alpha dm:today beta");
    let _ = parse_ok("dc:pastweek alpha beta");
    let _ = parse_ok("alpha beta dm:today");
    let _ = parse_ok("alpha beta dc:pastweek");
    let _ = parse_ok("alpha dm:today beta dc:pastweek");
    let _ = parse_ok("dm:today alpha beta dc:pastweek");
    let _ = parse_ok("alpha beta gamma dm:today");
    let _ = parse_ok("alpha beta gamma dc:pastweek");
    let _ = parse_ok("alpha dm:today beta gamma");
    let _ = parse_ok("dc:pastweek alpha beta gamma");
    let _ = parse_ok("alpha gamma dm:today beta");
    let _ = parse_ok("alpha gamma dc:pastweek beta");
    let _ = parse_ok("alpha beta gamma delta dm:today");
    let _ = parse_ok("alpha beta gamma delta dc:pastweek");
    let _ = parse_ok("alpha|beta gamma dm:today");
    let _ = parse_ok("alpha | beta gamma dc:pastweek");
    let _ = parse_ok("(alpha beta) | gamma dm:today");
    let _ = parse_ok("alpha | (beta gamma) dc:pastweek");
}
